export default {
  login: "FatimaLDL1997",
  id: 71790042,
  node_id: "MDQ6VXNlcjcxNzkwMDQy",
  avatar_url: "https://avatars.githubusercontent.com/u/71790042?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/FatimaLDL1997",
  html_url: "https://github.com/FatimaLDL1997",
  followers_url: "https://api.github.com/users/FatimaLDL1997/followers",
  following_url:
    "https://api.github.com/users/FatimaLDL1997/following{/other_user}",
  gists_url: "https://api.github.com/users/FatimaLDL1997/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/FatimaLDL1997/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/FatimaLDL1997/subscriptions",
  organizations_url: "https://api.github.com/users/FatimaLDL1997/orgs",
  repos_url: "https://api.github.com/users/FatimaLDL1997/repos",
  events_url: "https://api.github.com/users/FatimaLDL1997/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/FatimaLDL1997/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 13,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2020-09-23T19:25:34Z",
  updated_at: "2022-09-22T01:35:44Z",
};
